# Generated by Django 5.2.6 on 2026-05-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('credits', models.IntegerField(verbose_name='学分')),
                ('hours', models.IntegerField(verbose_name='课时')),
                ('description', models.TextField(blank=True, null=True, verbose_name='课程描述')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses',
            },
        ),
    ]
