"""
Django settings for sims project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# 构建项目路径，例如：BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent


# 快速开发设置 - 不适合生产环境
# 详情请查看：https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 安全警告：在生产环境中请保持密钥的安全性！
SECRET_KEY = 'django-insecure-+q^)+_3jn$bi!4c2y78sw3c)agalv-d%$8y)s=om9^%c#rb*z%'

# 安全警告：在生产环境中不要开启调试模式！
DEBUG = True

# 允许访问的主机列表
ALLOWED_HOSTS = []


# 应用定义

INSTALLED_APPS = [
    'django.contrib.admin',          # Django后台管理系统
    'django.contrib.auth',           # 认证系统
    'django.contrib.contenttypes',   # 内容类型框架
    'django.contrib.sessions',       # 会话管理
    'django.contrib.messages',       # 消息系统
    'django.contrib.staticfiles',    # 静态文件管理
    'student',                       # 自定义学生应用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',             # 安全中间件
    'django.contrib.sessions.middleware.SessionMiddleware',      # 会话中间件
    'django.middleware.common.CommonMiddleware',                 # 通用中间件
    'django.middleware.csrf.CsrfViewMiddleware',                # CSRF保护中间件
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # 认证中间件
    'django.contrib.messages.middleware.MessageMiddleware',      # 消息中间件
    'django.middleware.clickjacking.XFrameOptionsMiddleware',   # 点击劫持保护中间件
]

# 根URL配置
ROOT_URLCONF = 'sims.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # 模板引擎
        'DIRS': [],  # 模板目录
        'APP_DIRS': True,  # 是否在应用目录中查找模板
        'OPTIONS': {
            'context_processors': [  # 上下文处理器
                'django.template.context_processors.request',  # 请求上下文
                'django.contrib.auth.context_processors.auth',  # 认证上下文
                'django.contrib.messages.context_processors.messages',  # 消息上下文
                'django.template.context_processors.media',  # 媒体文件上下文
            ],
        },
    },
]

# WSGI应用配置
WSGI_APPLICATION = 'sims.wsgi.application'


# 数据库配置
# 详情请查看：https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # 使用SQLite数据库
        'NAME': BASE_DIR / 'db.sqlite3',  # 数据库文件路径
    }
}


# 密码验证
# 详情请查看：https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # 密码与用户属性相似度验证
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # 密码最小长度验证
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # 常见密码验证
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # 纯数字密码验证
    },
]


# 国际化配置
# 详情请查看：https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 语言代码，设置为中文

TIME_ZONE = 'Asia/Shanghai'  # 时区设置为上海

USE_I18N = True  # 启用国际化

USE_TZ = True  # 启用时区支持


# 静态文件配置（CSS, JavaScript, Images）
# 详情请查看：https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'  # 静态文件URL路径

# 默认主键字段类型
# 详情请查看：https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # 默认使用BigAutoField作为主键类型

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
