# Generated by Django 5.2.6 on 2026-04-29 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('student', '0002_student_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.class', verbose_name='班级'),
        ),
    ]
