# Generated by Django 5.2.6 on 2026-05-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0003_student_class_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='course.course', verbose_name='所选课程'),
        ),
    ]
